name: CopyCat
version: ${pom.version}

main: au.com.addstar.copycat.CopyCatPlugin

depend: [Minigames]

permissions:
  copycat.command.create:
    default: OP
  copycat.command.set:
    default: OP
  copycat.command.delete:
    default: OP
  copycat.command.editor:
    default: OP

commands:
  copycat: