name: CopyCat
version: ${pom.version}

main: au.com.addstar.copycat.CopyCatPlugin

depend: [Minigames]

permissions:
  copycat.command.create:
    default: OP
  copycat.command.set:
    default: OP
    
commands:
  copycat: